org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true

## Release keystore properties for signing a production build.
## Set these values in android/gradle.properties and do not commit secrets to version control.
MY_APP_KEY_ALIAS=africana_key
MY_APP_KEY_PASSWORD=PETERPETER
MY_APP_STORE_PASSWORD=PETERPETER
